### PR TITLE
REPO-4124 : Remove HttpOnly & Secure Attributes

### PR DESCRIPTION
**Pull request by Epurashu**
Remove HttpOnly & Secure cookie Attributes from tomcat level as they will be configured at reverse proxy level.

### CODE REVIEW

**Comment by killerboot** [comment]
If this goes forwards, please add more reviewers as it is the "base" image.

**Comment by melahn** [comment]
I don't seem to be able to add reviewers but would suggest @mteodori  and @montgolfiere at least review as well since they also consume the image.

Also suggest @philipmeadows review to check the assumption the cookie flags will be set somewhere else (in any case that should be tested in a pentest)

**Comment by montgolfiere** [comment]
@melahn JFYI, we consume alfresco-docker-base-java (not alfresco-docker-base-tomcat)

**Comment by mteodori** [comment]
is this a fix for this one? https://issues.alfresco.com/jira/browse/ACTIVITI-2527
aren't we missing the other vars mentioned there for https termination at the reverse proxy level?

**Comment by Epurashu** [comment]
As part of REPO-3275 -> https://issues.alfresco.com/jira/browse/REPO-3275 ( "Deployment: Secure tomcat in the Alfresco Content Services docker images with more advanced features" ). We decided to add secure &httpOnly flag to Cookies and enforce usage of HTTPS. 

As specified in RFC6265 -> https://tools.ietf.org/html/rfc6265#section-4.1.2.5 :
```When a cookie has the Secure attribute, the user agent will include the cookie in an HTTP request only if the request is transmitted over a secure channel (typically HTTP over Transport Layer Security (TLS)```

Web.xml
```
595    <session-config>
596        <session-timeout>30</session-timeout>
597        <cookie-config>
598            <http-only>true</http-only> 
599            <secure>true</secure>
600        </cookie-config>
601    </session-config>
```
Unfortunately we were not able to enforce usage of https to internal and external consumption, 

By adding Secure attribute to the session-cookie, application that use docker base-tomcat image will not work properly over http: e.g. Share login page. Alfresco activiti-admin page; Alfresco node-browser. 

Reactive methods have been taken until now, removing the Secure flag from web.xml:
Alfresco/process-services-docker -> https://github.com/Alfresco/process-services-docker/blob/master/activiti-admin/Dockerfile#L16
Alfresco/process-services-docker ->https://github.com/Alfresco/process-services-docker/blob/master/activiti-app/Dockerfile#L20
Alfresco/share -> https://github.com/Alfresco/share/blob/support/SP/6.1.N/packaging/docker/Dockerfile#L17

And corresponding issues:
ACTIVITI-2114 -> https://issues.alfresco.com/jira/browse/ACTIVITI-2114
SHA-2259 -> https://issues.alfresco.com/jira/browse/SHA-2259

For the Repo team, the following issues are affected by this:
ACE-5936 -> https://issues.alfresco.com/jira/browse/ACE-5936
ACE-5922 -> https://issues.alfresco.com/jira/browse/ACE-5922

**Comment by Epurashu** [comment]
> I don't seem to be able to add reviewers but would suggest @mteodori and @montgolfiere at least review as well since they also consume the image.
> 
> Also suggest @philipmeadows review to check the assumption the cookie flags will be set somewhere else (in any case that should be tested in a pentest)

Thank you for this suggestion, i have added @philipmeadows to this conversation.

At this time, ACS Deployment, both docker-compose and helm are behind a reverse-proxy (Nginx), our current plan is to configure HTTPS at proxy level not tomcat. In this case, the secure cookie flag would be used only over a secure channel (HTTPS). 

OWASP documentation states : (https://www.owasp.org/index.php/SecureFlag#Environment_consideration)
```In Tomcat 6 if the first request for session is using https then it automatically sets secure attribute on session cookie.```
I`m not sure if additional measures are required.

**Pull request merged**
